service: Python AWS Lambda Template

provider:
  name: aws
  runtime: 'python3.10'
  stage: prod
  region: eu-west-2
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

    # add any other environment variables here
    # that are stored in GitHub Secrets

  timeout: 60

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  wsgi:
    app: app.app
    packRequirements: false
  # uncomment below if you want to use a custom domain
  #customDomain:
  #  domainName: api.example.com
  #  basePath: ''
  #  stage: ${self:provider.stage}
  #  createRoute53Record: false
  #  certificateName: '*.example.com'
  #  endpointType: 'regional'
