name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.10.0
      

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Python Requirements plugin
        run: cd src && sls plugin install -n serverless-python-requirements

      - name: Install Serverless WSGI plugin
        run: cd src && sls plugin install -n serverless-wsgi

      - name: Install Serverless Domain Manager plugin
        run: cd src && sls plugin install -n serverless-domain-manager

      - name: Install Python dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Deploy to AWS Lambda
        run: cd src && sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}